server:
  port: 5001

spring:
  application:
    name: gateway
  cloud:
    # gateway???
    gateway:
      discovery:
        locator:
          enabled: true
      # ????
      routes:
        - id: demo_route # ???????? ??? order
          uri: lb://provider-server # ???????  lb???nacos??????????
          # uri: http://localhost:8002/demo #??????
          # ???? ?????????
          predicates:
            - Path=/pro-serv/**
          filters:
            - StripPrefix=1  # ???????????
              # http://localhost:5001/pro-serv/demo ??? http://localhost:5001/demo
    # ?? Nacos
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        group: demo