server:
  port: 5001

spring:
  application:
    name: gateway
  cloud:
    # gateway配置
    gateway:
      httpclient:
        #定义全局超时时间
        connect-timout: 1000
        response-timeout: 5s
      discovery:
        locator:
          enabled: true #从注册中心中获取服务
      ##将某些filter设置为默认，引用于所有的route
      default-filters:
        - AddResponseHeader=X-Response-Default-Demo, Demo
      # 路由配置
      routes:
        - id: demo_route #唯一标识
          uri: lb://provider-server #路由目标地址 lb://xxx 从注册中心中获取服务地址
          predicates:
            - Path=/pro-serv/**
          filters:
            - StripPrefix=1 #使用该过滤器将 http://localhost:5001/pro-serv/demo 转换为 http://localhost:5001/demo
          metadata:
            #单个route配置超时时间
            connect-timeout: 1000
            response-timeout: 2s
    # nacos配置
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        group: demo
